leftnav:
- identifier: 534c95e6-f48c-b558-62f0-a4b43ee31aa6
  name: Syllabus
  url: /pages/syllabus/
  weight: 10
- identifier: 232fc155-f77e-7b98-62d8-4d389de47251
  name: Pre-Pandemic Syllabus
  parent: 534c95e6-f48c-b558-62f0-a4b43ee31aa6
  url: /pages/syllabus/original-syllabus
  weight: 20
- identifier: 32051d6a-731a-f89d-9797-be2aafd7b891
  name: Calendar
  url: /pages/calendar
  weight: 30
- identifier: 7ab5c485-2253-798a-b1b6-aba790e8067e
  name: Instructor Insights
  url: /pages/instructor-insights
  weight: 40
- identifier: 94f5017c-4f2e-17c7-9cb2-8797b5e7db13
  name: Readings
  url: /pages/readings
  weight: 50
- identifier: cd4ff9f5-d886-36f8-5e19-cebe5a4a8d07
  name: Assignments
  url: /pages/assignments
  weight: 60
